In [59]:
import schedulers

import importlib
importlib.reload(schedulers)

from schedulers import LinearScheduler, CosineScheduler
from diffusion import Diffusion


import torch

from noise_distributions import normal_noise_like

In [64]:
def compare_coeffs(scheduler):
    # coeffs from Diffusion class
    diffuser = Diffusion(scheduler, normal_noise_like)
    betas = diffuser.scheduler.betas
    alphas = 1. - betas
    alphas_bar = torch.cumprod(1. - betas, dim=0)

    coeffs_1 = {"betas": betas, "alphas": alphas, "alphas_bar": alphas_bar}
    coeffs_2 = diffuser.coeffs

    coeffs_diff_dict = coeffs_1 | coeffs_2

    coeffs_diff_dict.pop("sqrt_one_minus_b")

    keys = coeffs_diff_dict.keys()
    coeffs_diff = coeffs_diff_dict.values()

    # coeffs from Scheduler class
    coeffs_sched = [scheduler.betas,
                    scheduler.alphas,
                    scheduler.alphas_bar,
                    #"-",
                    scheduler.sqrt_betas,
                    scheduler.sqrt_alphas_bar,
                    scheduler.sqrt_one_minus_alphas_bar,
                    scheduler.image_coeff,
                    scheduler.noise_coeff,]

    ########

    for name, s, d in zip(keys, coeffs_sched, coeffs_diff):
        h0 = float(s[0]) - float(d[0])
        h999 = float(s[-1]) - float(d[-1])
        print(h0, h999, name)


In [65]:
T = 1000

compare_coeffs(LinearScheduler(T))
print("")
compare_coeffs(CosineScheduler(T))

0.0 0.0 betas
0.0 0.0 alphas
0.0 0.0 alphas_bar
0.0 0.0 sqrt_b
0.0 0.0 sqrt_a_bar
0.0 0.0 sqrt_one_minus_a_bar
0.0 0.0 image_coeff
0.0 0.0 noise_coeff

0.0 0.0 betas
0.0 0.0 alphas
0.0 0.0 alphas_bar
0.0 0.0 sqrt_b
0.0 0.0 sqrt_a_bar
0.0 0.0 sqrt_one_minus_a_bar
0.0 0.0 image_coeff
0.0 0.0 noise_coeff


In [66]:
Diffusion(CosineScheduler(T), normal_noise_like).coeffs["image_coeff"]

tensor([ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,
         1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0001,  1.0001,  1.0001,
         1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,
         1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,
         1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,
         1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,
         1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0002,  1.0002,
         1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,
         1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,
         1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,
         1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,
         1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0003,  1.0003,
         1.0003,  1.0003,  1.0003,  1.00

In [67]:
CosineScheduler(T).image_coeff

tensor([ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,
         1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0001,  1.0001,  1.0001,
         1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,
         1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,
         1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,
         1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,
         1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0001,  1.0002,  1.0002,
         1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,
         1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,
         1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,
         1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,
         1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0002,  1.0003,  1.0003,
         1.0003,  1.0003,  1.0003,  1.00

In [68]:
Diffusion(CosineScheduler(T), normal_noise_like).scheduler.betas[[-2, -1]]

tensor([0.7500, 0.9990])